-- ================================================================
-- MELHORIA DA SINCRONIZAÇÃO IXC -> SUPABASE
-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Não apaga clientes, créditos ou pagamentos existentes.
-- ================================================================

-- Garante que a tabela de pagamentos possui as colunas usadas pela integração.
alter table public.game_pagamentos
  add column if not exists fatura_id varchar,
  add column if not exists cpf varchar,
  add column if not exists valor numeric(12,2),
  add column if not exists creditos integer,
  add column if not exists created_at timestamptz default now();

create unique index if not exists game_pagamentos_fatura_id_unique
  on public.game_pagamentos (fatura_id);

-- Marcador da última sincronização concluída.
create table if not exists public.game_sync_estado (
  id varchar primary key,
  ultima_sincronizacao timestamptz,
  atualizado_em timestamptz not null default now()
);

-- Histórico de cada execução do EasyCron.
create table if not exists public.game_sync_logs (
  id bigint generated by default as identity primary key,
  inicio_em timestamptz not null default now(),
  fim_em timestamptz,
  janela_inicio timestamptz,
  janela_fim timestamptz,
  datas_consultadas jsonb,
  encontradas integer not null default 0,
  novas integer not null default 0,
  creditadas integer not null default 0,
  duplicadas integer not null default 0,
  sem_creditos integer not null default 0,
  erros integer not null default 0,
  sucesso boolean not null default false,
  mensagem_erro text,
  detalhes jsonb
);

create index if not exists game_sync_logs_inicio_em_idx
  on public.game_sync_logs (inicio_em desc);

-- Função atômica: registra a fatura e soma os créditos somente uma vez.
drop function if exists public.game_adicionar_creditos(text, text, bigint, numeric, integer);

create or replace function public.game_adicionar_creditos(
  p_cpf text,
  p_nome text,
  p_fatura_id text,
  p_valor numeric,
  p_creditos integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inseriu integer := 0;
begin
  if coalesce(p_creditos, 0) < 1 then
    return false;
  end if;

  insert into public.game_pagamentos (fatura_id, cpf, valor, creditos)
  values (p_fatura_id, p_cpf, p_valor, p_creditos)
  on conflict (fatura_id) do nothing;

  get diagnostics inseriu = row_count;
  if inseriu = 0 then
    return false;
  end if;

  insert into public.game_clientes (cpf, nome, creditos)
  values (p_cpf, p_nome, p_creditos)
  on conflict (cpf) do update
     set nome = excluded.nome,
         creditos = public.game_clientes.creditos + excluded.creditos;

  return true;
end;
$$;

grant execute on function public.game_adicionar_creditos(
  text, text, text, numeric, integer
) to service_role;

-- Somente a chave de serviço usada pelas APIs pode acessar o controle e os logs.
alter table public.game_sync_estado enable row level security;
alter table public.game_sync_logs enable row level security;

revoke all on public.game_sync_estado from anon, authenticated;
revoke all on public.game_sync_logs from anon, authenticated;
grant all on public.game_sync_estado to service_role;
grant all on public.game_sync_logs to service_role;
grant usage, select on sequence public.game_sync_logs_id_seq to service_role;
