-- ATOS Telecom - Prêmios com estoque unitário e token único
-- Execute este arquivo no SQL Editor do Supabase antes do deploy.
create extension if not exists pgcrypto;

create table if not exists public.game_premios (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  quantidade integer not null default 0 check (quantidade >= 0),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.game_partidas (
  id uuid primary key default gen_random_uuid(),
  cpf varchar(11) not null,
  premio_resgatado boolean not null default false,
  criado_em timestamptz not null default now()
);
create index if not exists game_partidas_cpf_idx on public.game_partidas(cpf, criado_em desc);

create table if not exists public.game_premios_ganhos (
  id uuid primary key default gen_random_uuid(),
  partida_id uuid not null unique references public.game_partidas(id) on delete restrict,
  premio_id bigint not null references public.game_premios(id) on delete restrict,
  cpf varchar(11) not null,
  premio_nome text not null,
  status text not null default 'pendente',
  criado_em timestamptz not null default now(),
  entregue_em timestamptz
);

alter table public.game_premios_ganhos add column if not exists token_codigo text;
create unique index if not exists game_premios_ganhos_token_uidx
  on public.game_premios_ganhos(token_codigo) where token_codigo is not null;
create index if not exists game_premios_ganhos_cpf_idx on public.game_premios_ganhos(cpf, criado_em desc);

create table if not exists public.game_premio_tokens (
  id uuid primary key default gen_random_uuid(),
  premio_id bigint not null references public.game_premios(id) on delete cascade,
  codigo text not null unique,
  status text not null default 'disponivel' check (status in ('disponivel','reservado','resgatado','cancelado')),
  ganho_id uuid unique references public.game_premios_ganhos(id) on delete set null,
  criado_em timestamptz not null default now(),
  reservado_em timestamptz,
  resgatado_em timestamptz
);
create index if not exists game_premio_tokens_disp_idx on public.game_premio_tokens(premio_id,status);

insert into public.game_premios (nome, quantidade, ativo) values
  ('5% DE DESCONTO', 0, true),
  ('10% DE DESCONTO', 0, true),
  ('PIX DE R$ 30,00', 0, true),
  ('CHAVEIRO', 0, true),
  ('1 MÊS GRÁTIS DE INTERNET', 0, true)
on conflict (nome) do nothing;

create or replace function public.game_novo_token()
returns text language plpgsql volatile as $$
declare v text;
begin
  loop
    v := 'ATOS-' || upper(substr(encode(gen_random_bytes(8),'hex'),1,4)) || '-' ||
         upper(substr(encode(gen_random_bytes(8),'hex'),1,4)) || '-' ||
         upper(substr(encode(gen_random_bytes(8),'hex'),1,4));
    exit when not exists(select 1 from public.game_premio_tokens where codigo=v);
  end loop;
  return v;
end; $$;

-- Cria tokens para o estoque que já existia antes desta atualização.
do $$
declare r record; n integer;
begin
  for r in select id, quantidade from public.game_premios loop
    select count(*) into n from public.game_premio_tokens where premio_id=r.id and status='disponivel';
    while n < r.quantidade loop
      insert into public.game_premio_tokens(premio_id,codigo) values(r.id,public.game_novo_token());
      n := n + 1;
    end loop;
  end loop;
end $$;

create or replace function public.game_definir_estoque_premio(p_premio_id bigint, p_quantidade integer)
returns integer language plpgsql security definer set search_path=public as $$
declare atual integer; remover integer;
begin
  perform 1 from public.game_premios where id=p_premio_id for update;
  if not found then raise exception 'Prêmio não encontrado'; end if;
  p_quantidade := greatest(coalesce(p_quantidade,0),0);
  select count(*) into atual from public.game_premio_tokens where premio_id=p_premio_id and status='disponivel';
  while atual < p_quantidade loop
    insert into public.game_premio_tokens(premio_id,codigo) values(p_premio_id,public.game_novo_token());
    atual := atual + 1;
  end loop;
  remover := atual-p_quantidade;
  if remover > 0 then
    delete from public.game_premio_tokens where id in (
      select id from public.game_premio_tokens
      where premio_id=p_premio_id and status='disponivel'
      order by criado_em desc limit remover
    );
  end if;
  update public.game_premios set quantidade=p_quantidade, atualizado_em=now() where id=p_premio_id;
  return p_quantidade;
end; $$;

create or replace function public.game_usar_credito_partida(p_cpf text)
returns table(autorizado boolean, creditos_restantes integer, partida_id uuid)
language plpgsql security definer set search_path=public as $$
declare v_creditos integer; v_partida uuid; v_cpf text;
begin
  v_cpf:=regexp_replace(coalesce(p_cpf,''),'\\D','','g');
  select creditos into v_creditos from public.game_clientes where cpf=v_cpf for update;
  if v_creditos is null or v_creditos<1 then return query select false,greatest(coalesce(v_creditos,0),0),null::uuid; return; end if;
  update public.game_clientes set creditos=v_creditos-1,atualizado_em=now() where cpf=v_cpf;
  insert into public.game_partidas(cpf) values(v_cpf) returning id into v_partida;
  begin insert into public.game_movimentacoes(cpf,tipo,quantidade,saldo_apos) values(v_cpf,'partida',-1,v_creditos-1); exception when undefined_table or undefined_column then null; end;
  return query select true,v_creditos-1,v_partida;
end; $$;

create or replace function public.game_resgatar_premio(p_partida_id uuid,p_cpf text)
returns table(ok boolean,premio_id bigint,premio_nome text,quantidade_restante integer,token_codigo text)
language plpgsql security definer set search_path=public as $$
declare v_partida public.game_partidas%rowtype; v_premio public.game_premios%rowtype; v_token public.game_premio_tokens%rowtype; v_ganho uuid; v_cpf text;
begin
  v_cpf:=regexp_replace(coalesce(p_cpf,''),'\\D','','g');
  select * into v_partida from public.game_partidas where id=p_partida_id for update;
  if v_partida.id is null or v_partida.cpf<>v_cpf or v_partida.premio_resgatado then
    return query select false,null::bigint,null::text,null::integer,null::text; return;
  end if;
  select * into v_premio from public.game_premios where ativo=true and quantidade>0
    order by (-ln(greatest(random(),0.0000001))/quantidade) limit 1 for update skip locked;
  if v_premio.id is null then return query select false,null::bigint,null::text,0,null::text; return; end if;
  select * into v_token from public.game_premio_tokens where premio_id=v_premio.id and status='disponivel'
    order by random() limit 1 for update skip locked;
  if v_token.id is null then update public.game_premios set quantidade=0,atualizado_em=now() where id=v_premio.id; return query select false,null::bigint,null::text,0,null::text; return; end if;
  update public.game_premios set quantidade=greatest(quantidade-1,0),atualizado_em=now() where id=v_premio.id;
  insert into public.game_premios_ganhos(partida_id,premio_id,cpf,premio_nome,token_codigo)
    values(v_partida.id,v_premio.id,v_partida.cpf,v_premio.nome,v_token.codigo) returning id into v_ganho;
  update public.game_premio_tokens set status='reservado',ganho_id=v_ganho,reservado_em=now() where id=v_token.id;
  update public.game_partidas set premio_resgatado=true where id=v_partida.id;
  return query select true,v_premio.id,v_premio.nome,greatest(v_premio.quantidade-1,0),v_token.codigo;
end; $$;

create or replace function public.game_entregar_premio_token(p_token text)
returns table(ok boolean,mensagem text,premio_nome text,cpf text,status text)
language plpgsql security definer set search_path=public as $$
declare t public.game_premio_tokens%rowtype; g public.game_premios_ganhos%rowtype; cod text;
begin
  cod:=upper(trim(coalesce(p_token,'')));
  select * into t from public.game_premio_tokens where codigo=cod for update;
  if t.id is null then return query select false,'Token não encontrado',null::text,null::text,null::text; return; end if;
  select * into g from public.game_premios_ganhos where id=t.ganho_id for update;
  if t.status='resgatado' or g.status='entregue' then return query select false,'Este token já foi utilizado',g.premio_nome,g.cpf,'entregue'; return; end if;
  if t.status<>'reservado' or g.id is null then return query select false,'Token inválido para retirada',g.premio_nome,g.cpf,coalesce(g.status,t.status); return; end if;
  update public.game_premio_tokens set status='resgatado',resgatado_em=now() where id=t.id;
  update public.game_premios_ganhos set status='entregue',entregue_em=now() where id=g.id;
  return query select true,'Prêmio confirmado e token inutilizado',g.premio_nome,g.cpf,'entregue';
end; $$;

notify pgrst,'reload schema';
