-- ATOS Telecom - Estoque de prêmios e resgate atômico
create extension if not exists pgcrypto;

create table if not exists public.game_premios (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  quantidade integer not null default 0 check (quantidade >= 0),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.game_partidas (
  id uuid primary key default gen_random_uuid(),
  cpf varchar(11) not null,
  premio_resgatado boolean not null default false,
  criado_em timestamptz not null default now()
);

create index if not exists game_partidas_cpf_idx on public.game_partidas(cpf, criado_em desc);

create table if not exists public.game_premios_ganhos (
  id uuid primary key default gen_random_uuid(),
  partida_id uuid not null unique references public.game_partidas(id) on delete restrict,
  premio_id bigint not null references public.game_premios(id) on delete restrict,
  cpf varchar(11) not null,
  premio_nome text not null,
  status text not null default 'pendente',
  criado_em timestamptz not null default now(),
  entregue_em timestamptz
);

create index if not exists game_premios_ganhos_cpf_idx on public.game_premios_ganhos(cpf, criado_em desc);

insert into public.game_premios (nome, quantidade, ativo) values
  ('5% DE DESCONTO', 0, true),
  ('10% DE DESCONTO', 0, true),
  ('PIX DE R$ 30,00', 0, true),
  ('CHAVEIRO', 0, true),
  ('1 MÊS GRÁTIS DE INTERNET', 0, true)
on conflict (nome) do nothing;

create or replace function public.game_usar_credito_partida(p_cpf text)
returns table(autorizado boolean, creditos_restantes integer, partida_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_creditos integer;
  v_partida uuid;
begin
  select creditos into v_creditos
  from public.game_clientes
  where cpf = regexp_replace(coalesce(p_cpf,''), '\\D', '', 'g')
  for update;

  if v_creditos is null or v_creditos < 1 then
    return query select false, greatest(coalesce(v_creditos,0),0), null::uuid;
    return;
  end if;

  update public.game_clientes
  set creditos = v_creditos - 1, atualizado_em = now()
  where cpf = regexp_replace(coalesce(p_cpf,''), '\\D', '', 'g');

  insert into public.game_partidas(cpf)
  values (regexp_replace(coalesce(p_cpf,''), '\\D', '', 'g'))
  returning id into v_partida;

  begin
    insert into public.game_movimentacoes(cpf, tipo, quantidade, saldo_apos)
    values (regexp_replace(coalesce(p_cpf,''), '\\D', '', 'g'), 'partida', -1, v_creditos - 1);
  exception when undefined_table or undefined_column then
    null;
  end;

  return query select true, v_creditos - 1, v_partida;
end;
$$;

create or replace function public.game_resgatar_premio(p_partida_id uuid, p_cpf text)
returns table(ok boolean, premio_id bigint, premio_nome text, quantidade_restante integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_partida public.game_partidas%rowtype;
  v_premio public.game_premios%rowtype;
begin
  select * into v_partida
  from public.game_partidas
  where id = p_partida_id
  for update;

  if v_partida.id is null
     or v_partida.cpf <> regexp_replace(coalesce(p_cpf,''), '\\D', '', 'g')
     or v_partida.premio_resgatado then
    return query select false, null::bigint, null::text, null::integer;
    return;
  end if;

  -- Sorteio ponderado pelo estoque: mais unidades = maior chance.
  select * into v_premio
  from public.game_premios
  where ativo = true and quantidade > 0
  order by (-ln(greatest(random(), 0.0000001)) / quantidade)
  limit 1
  for update skip locked;

  if v_premio.id is null then
    return query select false, null::bigint, null::text, 0;
    return;
  end if;

  update public.game_premios
  set quantidade = quantidade - 1, atualizado_em = now()
  where id = v_premio.id;

  insert into public.game_premios_ganhos(partida_id, premio_id, cpf, premio_nome)
  values (v_partida.id, v_premio.id, v_partida.cpf, v_premio.nome);

  update public.game_partidas set premio_resgatado = true where id = v_partida.id;

  return query select true, v_premio.id, v_premio.nome, v_premio.quantidade - 1;
end;
$$;

notify pgrst, 'reload schema';
